{% set name = "julearn" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/julearn-{{ version }}.tar.gz
  sha256: ac5d283b6f30db48295de6e37c4567b91aac0a0cdc52e041356d6077c011322a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0.0
    - wheel
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.8
    - numpy >=1.24,<1.27
    - pandas >=1.5.0,<2.2
    - scikit-learn >=1.2.0,<1.5.0
    - statsmodels >=0.13,<0.15
    - panel >=1.3.0
    - bokeh >=3.0.0
    - param >=2.0.0
    - scikit-optimize >=0.10.0,<0.11
    - optuna >=3.6.0,<3.7
    - optuna-integration >=3.6.0,<3.7

test:
  imports:
    - julearn
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/juaml/julearn
  summary: Juelich Machine Learning Library
  license: AGPL-3.0-only
  license_file: LICENSE.md
  doc_url: https://juaml.github.io/julearn/main/index.html
  dev_url: https://github.com/juaml/julearn

extra:
  recipe-maintainers:
    - synchon
